version: '3.7'
services:
  postgres:
    image: postgres:12
    container_name: markinson-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: aoe4tv
